[project]
name = "sem-vi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=7.1.0",
    "matplotlib>=3.10.8",
    "scikit-learn>=1.8.0",
    "tensorflow>=2.20.0",
]
